name: push-build-release
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on: 
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened,reopened]
    branches: [develop]
jobs:
  configure-build-package-release:
    uses: EddyTheCo/Qb1t6/.github/workflows/build-test-install.yml@v0.0.1
